Add missing vector include
```
In file included from option_strings.cc:43:
./../../torrent/connection_manager.h:246:8: error: ‘vector’ in namespace ‘std’ does not name a template type
  246 |   std::vector<TrackerUdp*> m_tracker_udp_list;
      |        ^~~~~~
./../../torrent/connection_manager.h:51:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
   50 | #include <torrent/common.h>
  +++ |+#include <vector>
```